//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class kategorija
{
    public kategorija()
    {
        this.oglas = new HashSet<oglas>();
    }

    public int idkategorija { get; set; }
    public string nazivKategorije { get; set; }
    public string opis { get; set; }

    public virtual ICollection<oglas> oglas { get; set; }
}

public partial class komentar
{
    public int idkomentar { get; set; }
    public string naslov { get; set; }
    public string tekst { get; set; }
    public System.DateTime datumKreiranja { get; set; }
    public System.DateTime datumAzuriranja { get; set; }
    public int korisnik_idkorisnika { get; set; }
    public int oglas_idoglasa { get; set; }

    public virtual korisnik korisnik { get; set; }
    public virtual oglas oglas { get; set; }
}

public partial class korisnik
{
    public korisnik()
    {
        this.komentar = new HashSet<komentar>();
        this.poruka = new HashSet<poruka>();
    }

    public int idkorisnik { get; set; }
    public string ime { get; set; }
    public string prezime { get; set; }
    public string email { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string profil { get; set; }
    public string telefon { get; set; }
    public string boraviste { get; set; }

    public virtual ICollection<komentar> komentar { get; set; }
    public virtual ICollection<poruka> poruka { get; set; }
}

public partial class oglas
{
    public oglas()
    {
        this.komentar = new HashSet<komentar>();
    }

    public int idoglas { get; set; }
    public string naslov { get; set; }
    public string tekst { get; set; }
    public System.DateTime datumKreiranja { get; set; }
    public System.DateTime datumAzuriranja { get; set; }
    public int tutor_idtutor { get; set; }
    public int kategorija_idkategorija { get; set; }
    public int cijena { get; set; }
    public string portret { get; set; }
    public int strucnost_idstrucnost { get; set; }

    public virtual kategorija kategorija { get; set; }
    public virtual ICollection<komentar> komentar { get; set; }
    public virtual strucnost strucnost { get; set; }
    public virtual tutor tutor { get; set; }
}

public partial class poruka
{
    public int idporuka { get; set; }
    public string naslov { get; set; }
    public System.DateTime tekst { get; set; }
    public int datum { get; set; }
    public int korisnik_idkorisnik { get; set; }
    public int tutor_idtutor { get; set; }

    public virtual korisnik korisnik { get; set; }
    public virtual tutor tutor { get; set; }
}

public partial class strucnost
{
    public strucnost()
    {
        this.oglas = new HashSet<oglas>();
    }

    public int idstrucnost { get; set; }
    public string iskustvo { get; set; }

    public virtual ICollection<oglas> oglas { get; set; }
}

public partial class tutor
{
    public tutor()
    {
        this.oglas = new HashSet<oglas>();
        this.poruka = new HashSet<poruka>();
    }

    public int idtutor { get; set; }
    public string ime { get; set; }
    public string prezime { get; set; }
    public string kvalifikacija { get; set; }
    public string email { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string profil { get; set; }
    public string telefon { get; set; }
    public string boraviste { get; set; }
    public string opis { get; set; }

    public virtual ICollection<oglas> oglas { get; set; }
    public virtual ICollection<poruka> poruka { get; set; }
}
