//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class bazaEntities : DbContext
{
    public bazaEntities()
        : base("name=bazaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<kategorija> kategorija { get; set; }
    public DbSet<komentar> komentar { get; set; }
    public DbSet<korisnik> korisnik { get; set; }
    public DbSet<oglas> oglas { get; set; }
    public DbSet<poruka> poruka { get; set; }
    public DbSet<strucnost> strucnost { get; set; }
    public DbSet<tutor> tutor { get; set; }
}
