//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        public int idkorisnik { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string profil { get; set; }
        public string telefon { get; set; }
        public string boraviste { get; set; }
    }
}
